# ----
# Site

title: "Redis Client"
description: "Redis Client allows to manage and send custom payload to redis using REST apis"
url: https://rediscli.carloslapao.com
google_analytics_key:
permalink: pretty
baseurl: ""

# -----
# Build

timezone: Etc/UTC

collections:
  documentation:
    title: Documentation
    position_number: 1
  api:
    title: APIs
    position_number: 2
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - readme.md
  - LICENSE

defaults:
  - scope:
      path: ""
    values:
      layout: default
  - scope:
      type: "documentation"
    values:
      _hide_content: true
  - scope:
      type: "api"
    values:
      _hide_content: true

# -----------
# CloudCannon

types:
  - get
  - put
  - delete
  - post

languages:
  bash: Bash
  c: C
  css: CSS
  html: HTML
  java: Java
  javascript: JavaScript
  json: JSON
  php: PHP
  python: Python
  ruby: Ruby

_options:
  content_markdown:
    format: p h4 h5 h6
    bold: true
    italic: true
    link: true
    bulletedlist: true
    numberedlist: true
    image: true
    table: true
    styles: /css/editor.css
